#!/bin/bash
#
# Adam Tavares
# 2014-08-06
#
# Usage: giffy sketch_name
#
# Used with gif_eyecandy.  
# Requires ImageMagick.
# Will build an animated gif file from the output in /var/www/gif_eyecandy/tmp

dir="/var/www/gif_eyecandy"
frames="$dir/tmp/f*.gif"
last=`find $dir | egrep -e "[0-9].gif" | sed 's/[^0-9]//g'| sort | tail -1`
name=$((last+1))
echo $name
gif="$dir/gifs/$name.gif"

if [ name == "new" ]; then
	echo "Add new feature, Adam"
elif [ name == "clean" ]; then
	echo "Add clean feature, Adam"
else
	convert -delay 3 -loop 0 $frames $gif
	rm $frames
	pushd $dir
	git add .
	git commit -m "Added $name.gif"
	popd
fi