#!/bin/bash
#
# Adam Tavares
# 2014-08-06
#
# Usage: giffy sketch_name
#
# Used with gif_eyecandy.  
# Requires ImageMagick.
# Will build an animated gif file from the output in /var/www/gif_eyecandy/tmp

frames="/var/www/gif_eyecandy/tmp/f*.gif"
name=$(echo "$1" | sed 's/\/$//'); shift
gif="/var/www/gif_eyecandy/gifs/$name.gif"

if [ name == "new" ]; then
	echo "Add new feature, Adam"
elif [ name == "clean" ]; then
	echo "Add clean feature, Adam"
else
	convert -delay 3 -loop 0 $frames $gif
	rm $frames
fi
