#!/bin/sh
#
# Adam Tavares
# Dec 18, 2013
#
# Usage: Add it to your PATH and `git-wipe`.
#
# Wipe the current Git repository clean resetting everything back to state in origin.
#
git fetch
git reset --hard origin/master